
systemLog:
  destination: file
  path: /proc/self/fd/1 # stdout
  logAppend: true
  quiet: true
  verbosity: 0

net:
  bindIpAll: true
  port: 27017

# CORE OPTIMIZATION: Drastically limit WiredTiger Cache
storage:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5
    collectionConfig:
      blockCompressor: snappy
    indexConfig:
      prefixCompression: true

# Disable profiling for a read-only database
operationProfiling:
  mode: off

# Minimize oplog footprint
replication:
  oplogSizeMB: 64
