FROM quay.io/keycloak/keycloak:latest AS builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

COPY build.conf /opt/keycloak/conf

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build --config-file=/opt/keycloak/conf/build.conf

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

CMD ["start", "--optimized"]
