FROM quay.io/keycloak/keycloak:latest AS builder

COPY keycloak.conf /opt/keycloak/conf/

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build
RUN /opt/keycloak/bin/kc.sh show-config

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

CMD ["start", "--optimized"]
