-- Grant minimal privileges
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON chat.* TO 'chat'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON login.* TO 'login'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON quiz.* TO 'quiz'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON sloth.* TO 'sloth'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON stats.* TO 'stats'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `keycloak_db`.* TO 'keycloak'@'%';
